### ISSUE TITLE
Add more C++ based programs!!

### ISSUE THREAD

**Issue by Dimplesinha** [fineanmol/Hacktoberfest2k21#461]
I would like to add more c++ based programs

**Comment by soumyajit1999** [comment]
Hello I would like to add c++ based pogram

**Comment by Abhinab21** [comment]
I would like to add c++ based program

**Comment by Adityadamen** [comment]
I would like to add c++ based program

**Comment by C0mRD** [comment]
Hello Please assign me this . I would like to add more c++ based programs .

**Comment by TahuTech** [comment]
Hello i can add more c++ programs.

**Comment by ShreyaTarwey** [comment]
Hello @fineanmol , could you please assign this issue to me , so I can start working on it.
I would be grateful to get a chance to work on this!
